---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - fail: msg="This playbook requires '-e target=<targethost>'"
    when: target is undefined

- hosts: "{{ target }}"
  name: Install Gopherbot
  remote_user: build
  become: yes
  tasks:
  - name: Create robot private group
    group:
      name: "{{ gopherbot_group }}"
      system: yes
  - name: Create user for robot
    user:
      name: "{{ gopherbot_user }}"
      system: yes
  - name: Create ssh directory
    file:
      path: "{{ gopherbot_home }}/.ssh"
      owner: "{{ gopherbot_user }}"
      group: "{{ gopherbot_group }}"
      state: directory
      mode: 0700
  - name: Clone the config repository
    block:
    - yum:
        name: git
        state: present
    - file:
        path: "{{ gopherbot_config_directory }}"
        state: directory
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0750
    - git:
        repo: "{{ gopherbot_config_repository }}"
        dest: "{{ gopherbot_config_directory }}"
      become_user: "{{ gopherbot_user }}"
  - name: Install the robot's SSH key
    copy:
        src: "files/{{ inventory_hostname }}/id_rsa"
        dest: "{{ gopherbot_home }}/.ssh/id_rsa"
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0600
  - name: Install the robot's SSH config
    copy:
        src: "files/{{ inventory_hostname }}/ssh-config"
        dest: "{{ gopherbot_home }}/.ssh/config"
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0600
  - import_role:
      name: lnxjedi.gopherbot
