---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - fail: msg="This playbook requires '-e target=<targethost>'"
    when: target is undefined

- hosts: "{{ target }}"
  name: Set vars and wait for DNS
  connection: local
  tasks:
  - name: Waiting for DNS to sync
    command: echo
    until: "lookup('dig', ansible_host ) == ec2_private_ip_address or lookup('dig', ansible_host ) == ec2_ip_address"
    retries: 60
    delay: 7
    changed_when: false
    when: ec2_ip_address is defined
  - name: Wait for SSH
    wait_for: host={{ ansible_host }} port=22 search_regex=OpenSSH

- hosts: "{{ target }}"
  become: yes
  tasks:
  - name: Hostname
    hostname: name={{ ansible_ssh_host }}
  - name: Hosts file
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 {{ ansible_ssh_host }} localhost.localdomain localhost'
  - name: sysconfig network
    lineinfile: 'dest=/etc/sysconfig/network regexp="^HOSTNAME=" line="HOSTNAME={{ ansible_ssh_host }}"'

# Generate new host keys or restore previous
- hosts: "{{ target }}"
  name: Re-use old host keys or store new ones
  become: yes
  tasks:
  - local_action: stat path="files/hostkeys/{{ inventory_hostname }}.tar.gz"
    register: hkeys
  - block:
    - name: Create archive of host keys
      shell: tar czf /tmp/{{ inventory_hostname }}-keys.tar.gz ssh_host_*
      args:
        chdir: /etc/ssh
    - name: Fetch host keys
      fetch: src=/tmp/{{ inventory_hostname }}-keys.tar.gz dest=files/hostkeys/{{ inventory_hostname }}.tar.gz flat=yes
    when: hkeys.stat is defined and not hkeys.stat.exists
  - block:
    - name: Restore host keys
      unarchive: src=files/hostkeys/{{ inventory_hostname }}.tar.gz dest=/etc/ssh
    - name: Restart SSH to read host keys
      service: name=sshd state=restarted
    when: hkeys.stat is defined and hkeys.stat.exists

- hosts: "{{ target }}"
  name: Add devel user(s)
  become: yes
  tasks:
  - name: Create group
    group:
      name: "{{ item.username }}"
    with_items: "{{ users }}"
  - name: Create user
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      groups: "{{ item.groups }}"
      comment: "{{ item.name }}"
    with_items: "{{ users }}"
  - name: Add ssh public key(s)
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ item.ssh_key }}"
    with_items: "{{ users }}"

- hosts: "{{ target }}"
  name: Install Gopherbot
  become: yes
  tasks:
  - name: Create robot private group
    group:
      name: "{{ gopherbot_group }}"
  - name: Create user for robot
    user:
      name: "{{ gopherbot_user }}"
      group: "{{ gopherbot_group }}"
      groups: [ "wheel" ]
  - name: Create ssh directory
    file:
      path: "{{ gopherbot_home }}/.ssh"
      owner: "{{ gopherbot_user }}"
      group: "{{ gopherbot_group }}"
      state: directory
      mode: 0700
  - name: Install the robot's SSH private key
    copy:
        src: "files/{{ inventory_hostname }}/id_rsa"
        dest: "{{ gopherbot_home }}/.ssh/id_rsa"
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0600
  - name: Install the robot's SSH public key
    copy:
        src: "files/{{ inventory_hostname }}/id_rsa.pub"
        dest: "{{ gopherbot_home }}/.ssh/id_rsa.pub"
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0644
  - name: Install the robot's SSH config
    copy:
        src: "files/{{ inventory_hostname }}/ssh-config"
        dest: "{{ gopherbot_home }}/.ssh/config"
        owner: "{{ gopherbot_user }}"
        group: "{{ gopherbot_group }}"
        mode: 0600
  - import_role:
      name: lnxjedi.gopherbot
